NewsManagerJSF/src/main/java/com/epam/news2/model/News.java
package com.epam.news2.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.NamedQueries;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;

import java.sql.Date;

@Entity
@NamedQueries({
	@NamedQuery(name="select_all", query ="select c from News c order by c.date desc"),
	@NamedQuery(name="delete", query ="delete from News c WHERE c.id in (:ID)")
}) 
@Table(name="NEWSTABLE")
public final class News implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String title;
	private Date date; 
	private String brief;
	private String content;
	
	@Id
	@SequenceGenerator(name = "ID", sequenceName = "NEWS_INCREMENT")
	@GeneratedValue(generator = "ID")
	@Column(name = "ID")
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "TITLE")
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	
	@Column(name = "NEWS_DATE")
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	
	@Column(name = "BRIEF")
	public String getBrief() {
		return brief;
	}
	public void setBrief(String brief) {
		this.brief = brief;
	}
	
	@Column(name = "CONTENT")
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
}

NewsManagerJSF/src/main/java/com/epam/news2/backing/LanguageBean.java
package com.epam.news2.backing;

import java.io.Serializable;
import java.util.Locale;
 
import javax.faces.context.FacesContext;
 
public final class LanguageBean implements Serializable{
 
	private static final long serialVersionUID = 1L;

	private Locale locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();

    public Locale getLocale() {
        return locale;
    }

    public String getLanguage() {
        return locale.getLanguage();
    }

    public void setLanguage(String language) {
        locale = new Locale(language);
        FacesContext.getCurrentInstance().getViewRoot().setLocale(locale);
    }
}

NewsManagerJSF/src/main/java/com/epam/news2/backing/NewsBean.java
package com.epam.news2.backing;

import com.epam.news2.model.News;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
 
public final class NewsBean implements Serializable {
 
	private static final long serialVersionUID = 1L;
 
	private List<News> newsList = new ArrayList<News>();
	private News currentNews = new News();
	private Map<Integer, Boolean> selectedNews = new HashMap<Integer, Boolean>();

	public List<News> getNewsList() {
		return newsList;
	}

	public void setNewsList(List<News> newsList) {
		this.newsList = newsList;
	}
	
	public News getCurrentNews() {
		return currentNews;
	}

	public void setCurrentNews(News currentNews) {
		this.currentNews = currentNews;
	}
	
	public Map<Integer, Boolean> getSelectedNews() {
		return selectedNews;
	}

	public void setSelectedNews(Map<Integer, Boolean> selectedNews) {
		this.selectedNews = selectedNews;
	}
}

NewsManagerJSF/src/main/java/com/epam/news2/controller/PageController.java
package com.epam.news2.controller;

import java.io.Serializable;
import java.sql.Date;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;

import org.apache.log4j.Logger;

import com.epam.news2.backing.NewsBean;
import com.epam.news2.dao.INewsDAO;
import com.epam.news2.exception.NewsManagerException;
import com.epam.news2.model.News;
import com.epam.news2.util.NewsUtilities;

public final class PageController implements Serializable {
 
	private static final long serialVersionUID = 1L;
	private static final String NEWS = "news";
	private static final String VIEW = "view";
	private static final String EDIT = "edit";
	private static final String IS_ADD_PAGE = "isAddPage";
	private static final String IS_EDIT_PAGE = "isEditPage";
	private static final String REDIRECT = "?faces-redirect=true";
	private static final Logger logger = Logger.getLogger(PageController.class);
	
	private NewsBean newsBean;
	private INewsDAO newsDAO;
	private String previousPage = "news";
	
	@PostConstruct
	public void init() {
		showNews();
	}

	public String showNews() {
		try {
			newsBean.setNewsList(newsDAO.getNewsList());
			newsBean.setSelectedNews(new HashMap<Integer, Boolean>());
			previousPage = NEWS;
		} catch (NewsManagerException ex) {
			logger.error(ex.getMessage());
		}
	    return NEWS; 
	}
	
	public String addNews() {
		setPageTypeToAdd(true);
		News news = new News();
		news.setDate(new Date(System.currentTimeMillis()));
		newsBean.setCurrentNews(news);
	    return EDIT; 
	}
	
	public String editNews() {
		setPageTypeToAdd(false);
		return EDIT; 
	}
	
	public String editNews(int id) {
		setPageTypeToAdd(false);
		try {
			newsBean.setCurrentNews(newsDAO.getCurrentNews(id));
		} catch (NumberFormatException | NewsManagerException ex) {
			logger.error(ex.getMessage());
		}
	    return EDIT; 
	}
	
	public String viewNews(int id) {
		try {
			newsBean.setCurrentNews(newsDAO.getCurrentNews(id));
			newsBean.setSelectedNews(new HashMap<Integer, Boolean>());
			newsBean.getSelectedNews().put(id, true);
			previousPage = VIEW;
		} catch (NumberFormatException | NewsManagerException ex) {
			logger.error(ex.getMessage());
		}
		return VIEW;
	}
	
	public String saveNews() {
		try {
			newsDAO.addNews(newsBean.getCurrentNews());
		} catch (NewsManagerException ex) {
			logger.error(ex.getMessage());
		}
		return viewNews(newsBean.getCurrentNews().getId()) + REDIRECT;
	}
	
	public String updateNews() {
		try {
			newsDAO.editNews(newsBean.getCurrentNews());
		} catch (NewsManagerException ex) {
			logger.error(ex.getMessage());
		}
		return viewNews(newsBean.getCurrentNews().getId());
	}
	
	public String deleteNews() {
		try {
			List<Integer> listToDelete = new ArrayList<Integer>();
			for (Integer id : newsBean.getSelectedNews().keySet()) {
				if(newsBean.getSelectedNews().get(id)) {
					listToDelete.add(id);
				}
			}
			Integer[] arrayToDelete;
			if (listToDelete.isEmpty()) {
				arrayToDelete = new Integer[1];
				arrayToDelete[0] = newsBean.getCurrentNews().getId();
				newsDAO.removeNews(arrayToDelete);
			} else {
				arrayToDelete = new Integer[listToDelete.size()];
				newsDAO.removeNews(listToDelete.toArray(arrayToDelete));
			}
		} catch (NewsManagerException ex) {
			logger.error(ex.getMessage());
		}
		return showNews() + REDIRECT;
	}
	
	public String getMessagesAsJson() {
		Locale locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();
		return NewsUtilities.getMessagesAsJson(locale);
	}
	
	private void setPageTypeToAdd(boolean isAddPage) {
		FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put(
				IS_ADD_PAGE, isAddPage ? true : false);
		FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put(
				IS_EDIT_PAGE, isAddPage ? false : true);
	}

	public NewsBean getNewsBean() {
		return newsBean;
	}

	public void setNewsBean(NewsBean newsBean) {
		this.newsBean = newsBean;
	}
	
	public INewsDAO getNewsDAO() {
		return newsDAO;
	}

	public void setNewsDAO(INewsDAO newsDAO) {
		this.newsDAO = newsDAO;
	}
	
	public String getPreviousPage() {
		return previousPage;
	}

	public void setPreviousPage(String previousPage) {
		this.previousPage = previousPage;
	}
}

NewsManagerJSF/src/main/webapp/pages/common/content.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
		xmlns:ui="http://java.sun.com/jsf/facelets">
    <body>
	    <ui:composition></ui:composition>
    </body>
</html>

NewsManagerJSF/src/main/webapp/pages/common/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
		xmlns:h="http://java.sun.com/jsf/html" 
		xmlns:ui="http://java.sun.com/jsf/facelets">
    <body>
	    <ui:composition>
			<h:outputText value="#{msg['label.common.footer']}" />
	    </ui:composition>
    </body>
</html>

NewsManagerJSF/src/main/webapp/pages/common/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
		xmlns:h="http://java.sun.com/jsf/html" 
		xmlns:ui="http://java.sun.com/jsf/facelets">
    <body>
	    <ui:composition>
			<h1>
				<h:outputText value="#{msg['label.common.header']}" />
			</h1>
			<h:form style="display: inline;">
				<h:commandLink action="#{languageBean.setLanguage('en')}"
						value="#{msg['label.common.english']}"/>
			</h:form>
			<h:form style="display: inline;">
				<h:commandLink action="#{languageBean.setLanguage('ru')}"
						value="#{msg['label.common.russian']}"/>
			</h:form>
	    </ui:composition>
    </body>
</html>

NewsManagerJSF/src/main/webapp/pages/common/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://java.sun.com/jsf/html" 
		xmlns:ui="http://java.sun.com/jsf/facelets">
    <body>
	    <ui:composition>
			<h2>
				<h:outputText value="#{msg['label.common.news']}" />
			</h2>
			<ul>
				<li>
					<h:form>
						<h:commandLink action="#{pageController.showNews}"
							value="#{msg['label.common.list']}" />
					</h:form>
				</li>
				<li>
					<h:form>
						<h:commandLink action="#{pageController.addNews}"
							value="#{msg['label.common.addnews']}" />
					</h:form>
				</li>
			</ul>
	    </ui:composition>
    </body>
</html>

NewsManagerJSF/src/main/webapp/pages/common/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
		<h:outputStylesheet library="css" name="style.css"  />
		<h:outputScript library="js" name="scripts.js" />
    	<script type="text/javascript">
			var messages = #{pageController.messagesAsJson};
		</script>
    </h:head>
    <h:body>
		<f:view locale="#{languageBean.locale}">
			<div id="page">
			    <div id="header">
					<ui:insert name="header" >
						<ui:include src="/pages/common/header.xhtml" />
					</ui:insert>
			    </div>
			    <div id="menu">
				  	<ui:insert name="menu" >
				 		<ui:include src="/pages/common/menu.xhtml" />
				   	</ui:insert>
			    </div>
			    <div id="content">
				  	<ui:insert name="content" >
				 		<ui:include src="/pages/common/content.xhtml" />
				   	</ui:insert>
			    </div>
			    <div id="footer">
			    	<ui:insert name="footer" >
			    		<ui:include src="/pages/common/footer.xhtml" />
			    	</ui:insert>
	    	    </div>
	        </div>
    	</f:view>
    </h:body>
</html>

NewsManagerJSF/src/main/webapp/pages/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"    
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head></h:head>
    <h:body>
    	<ui:composition template="/pages/common/template.xhtml">
 			<ui:define name="content">
 				<h:form style="display: inline;">
					<h:commandLink action="#{pageController.showNews}"
						value="#{msg['label.common.news']}" />
				</h:form>
				<h:outputText rendered="#{isAddPage}" 
						value="#{msg['label.common.section.add']}"/>
 				<h:outputText rendered="#{isEditPage}" 
 						value="#{msg['label.common.section.edit']}"/>
 				<h:form id="form" onsubmit="return validate();">
	 				<table id="view" cellspacing="20px">
					    <tr>
					        <td id="view-first-column">
					        	<h:outputText value="#{msg['label.common.table.title']}"/>
					        </td>
					        <td id="view-second-column">
					        	<h:inputText id="title" value="#{newsBean.currentNews.title}" 
					        			required="true" requiredMessage="#{msg['error.message.required.title']}"
					        			name="title">
					        		<f:validator validatorId="com.epam.news2.validation.TitleValidator"/>
					        		<f:attribute name="message" value="#{msg['error.message.maxlength.title']}" />
					        	</h:inputText>
					        	<h:message for="title" style="color:red"/>
							</td>
					    </tr>
					    <tr>
					        <td id="view-first-column">
					        	<h:outputText value="#{msg['label.common.table.date']}"/>
					        </td>
					        <td id="view-second-column">
					        	<h:inputText id="date" value="#{newsBean.currentNews.date}"
					        			required="true" requiredMessage="#{msg['error.message.required.date']}"
					        			name="date">
					        		<f:converter converterId="com.epam.news2.convert.DateConverter"/>
					        		<f:validator validatorId="com.epam.news2.validation.DateValidator"/>
					        		<f:attribute name="message" value="#{msg['error.message.format.date']}" />
					        	</h:inputText>
					        	<h:message for="date" style="color:red"/>
							</td>
					    </tr>
					    <tr>
					    	<td id="view-first-column">
					        	<h:outputText value="#{msg['label.common.table.brief']}"/>
					        </td>
					        <td id="view-second-column">
					        	<h:inputTextarea id="brief" value="#{newsBean.currentNews.brief}" 
					        			required="true" requiredMessage="#{msg['error.message.required.brief']}"
					        			style="width: 400px; height: 100px;" name="brief"/>
								<h:message for="brief" style="color:red"/>
							</td>
					    </tr>
					    <tr>
					    	<td id="view-first-column">
					        	<h:outputText value="#{msg['label.common.table.content']}"/>
					        </td>
					        <td id="view-second-column">
					        	<h:inputTextarea id="content" value="#{newsBean.currentNews.content}" 
					        			required="true" requiredMessage="#{msg['error.message.required.content']}"
					        			style="width: 400px; height: 200px;" name="content"/>
								<h:message for="content" style="color:red"/>
							</td>
					    </tr>
					</table>
					<div id="edit-button">
						<h:commandButton value="#{msg['label.common.button.update']}" 
								rendered="#{isEditPage}" action="#{pageController.updateNews}"/>
						<h:commandButton value="#{msg['label.common.button.update']}" 
								rendered="#{isAddPage}" action="#{pageController.saveNews}"/>
					</div>
				</h:form>
					<h:form>
						<h:commandButton value="#{msg['label.common.button.cancel']}" 
								rendered="#{isEditPage}" action="#{pageController.getPreviousPage}" immediate="true"/>
						<h:commandButton value="#{msg['label.common.button.cancel']}" 
								rendered="#{isAddPage}" action="news"/>
					</h:form>
 			</ui:define>
 		</ui:composition>
 	</h:body>
 </html>

NewsManagerJSF/src/main/webapp/pages/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Redirecting...</title>
        <meta http-equiv="refresh" content="1;url=faces/pages/news.xhtml" />
    </head>
    <body></body>
</html>

NewsManagerJSF/src/main/webapp/pages/news.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"    
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head></h:head>
    <h:body>
    	<ui:composition template="/pages/common/template.xhtml">
 			<ui:define name="content">
 				<h:form style="display: inline;">
					<h:commandLink action="#{pageController.showNews}"
						value="#{msg['label.common.news']}" />
				</h:form>
 				<h:outputText value="#{msg['label.common.section.list']}" />
 				<div id="news-list">
 					<h:form onsubmit="return deleteNews();">
	 					<ui:repeat value="#{newsBean.newsList}" var="news" style="width: 100%;">
			    			<h:column>
			    				<br/>
					            <div id="news-list-title">
					                <h:outputText value="#{news.title}"/>
					            </div>
					            <div id="news-list-date">
					            	<h:outputText value="#{news.date}">
					            		<f:converter converterId="com.epam.news2.convert.DateConverter" />
					            	</h:outputText>
					            </div>
					            <br/>
					            <div id="news-list-brief">
					                <h:outputText value="#{news.brief}"/>
					            </div>
					            <div id="control">
									<h:commandLink action="#{pageController.viewNews(news.id)}"
											value="#{msg['label.common.viewtitle']}"/>
									&nbsp;&nbsp;
									<h:commandLink action="#{pageController.editNews(news.id)}"
											value="#{msg['label.common.edit']}"/>
											
									<h:selectBooleanCheckbox styleClass="selected"
									 		value="#{newsBean.selectedNews[news.id]}" />
					            </div>
				            	<br/>
			    			</h:column>
			    		</ui:repeat>
			    		<div id="delete">
							<h:commandButton value="#{msg['label.common.button.delete']}" 
									action="#{pageController.deleteNews}"
									rendered="#{not(empty newsBean.newsList)}"/>
						</div>
 					</h:form>
 				</div>
			</ui:define>
    	</ui:composition>
    </h:body>
</html>

NewsManagerJSF/src/main/webapp/pages/view.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"    
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head></h:head>
    <h:body>
    	<ui:composition template="/pages/common/template.xhtml">
 			<ui:define name="content">
 				<h:form style="display: inline;">
					<h:commandLink action="#{pageController.showNews}"
						value="#{msg['label.common.news']}" />
				</h:form>
 				<h:outputText value="#{msg['label.common.section.view']}" />
 				<table id="view" cellspacing="20px">
				    <tr>
				        <td id="view-first-column">
				        	<h:outputText value="#{msg['label.common.table.title']}" />
				        </td>
				        <td id="view-second-column">
				        	<h:outputText value="#{newsBean.currentNews.title}" />
				        </td>
				    </tr>
				    <tr>
				        <td id="view-first-column">
				        	<h:outputText value="#{msg['label.common.table.date']}" />
				        </td>
				        <td id="view-second-column">
				        	<h:outputText value="#{newsBean.currentNews.date}">
				            		<f:converter converterId="com.epam.news2.convert.DateConverter" />
				            	</h:outputText>
				        </td>
				    </tr>
				    <tr>
				        <td id="view-first-column">
				        	<h:outputText value="#{msg['label.common.table.brief']}" />
				        </td>
				        <td id="view-second-column">
				        	<h:outputText value="#{newsBean.currentNews.brief}" />
				        </td>
				    </tr>
				    <tr>
				        <td id="view-first-column">
				        	<h:outputText value="#{msg['label.common.table.content']}" />
				        </td>
				        <td id="view-second-column">
				        	<h:outputText value="#{newsBean.currentNews.content}" />
				        </td>
				    </tr>
				</table>
				<div id="delete">
				    <div id="floater">
				        <h:form onsubmit="return deleteNews();">
				        	<h:commandButton action="#{pageController.deleteNews}"
				        			value="#{msg['label.common.button.delete']}"/>
				        </h:form>
				    </div>
				    <h:form>
				    	<h:commandButton action="#{pageController.editNews}" 
				    			value="#{msg['label.common.button.edit']}"/>
				    </h:form>
				</div>
 			</ui:define>
 		</ui:composition>
 	</h:body>
 </html>